In [2]:
import os, sys

# codepath = '/user_data/mmhender/image_stats_gabor/code/'
# sys.path.insert(0,codepath)

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import scipy.stats
import cmocean

from plotting import plot_utils, summary_plots, load_fits
from utils import roi_utils, default_paths, prf_utils
from feature_extraction import gabor_feature_extractor

In [7]:
from model_fitting import initialize_fitting
initialize_fitting

<module 'model_fitting.initialize_fitting' from '/user_data/mmhender/modfit/code/model_fitting/initialize_fitting.py'>

In [20]:
labels_all, discrim_type_list, unique_labs_each = \
    initialize_fitting.load_highlevel_labels_each_prf(1,5,np.arange(10000),models=np.arange(1456),debug=False)

loading labels from folders at /user_data/mmhender/nsd/labels/S1_within_prf_grid5 (will be slow...)
['face-building', 'animate-inanimate', 'small-large', 'indoor-outdoor']
num nans each column (out of 10000 trials):
[8960 3829 6006  785]


In [22]:
np.mean(np.isnan(labels_all[:,:,1400]), axis=0)

array([0.5985, 0.5282, 0.4072, 0.0785])

In [15]:
np.mean(labels_all[:,:,0]==1, axis=0)

array([0.0596, 0.3169, 0.2174, 0.6208])

In [17]:
np.mean(labels_all[:,:,0]==0, axis=0)

array([0.0444, 0.3002, 0.182 , 0.3007])

In [19]:
unique_labs_each

[array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1])]

In [2]:
from utils import coco_utils

Initializing coco api...
loading annotations into memory...
Done (t=0.72s)
creating index...
index created!
loading annotations into memory...
Done (t=16.30s)
creating index...
index created!
Initializing coco api...
loading annotations into memory...
Done (t=0.55s)
creating index...
index created!
loading annotations into memory...
Done (t=13.78s)
creating index...
index created!


In [2]:
n_sf=4; n_ori=4;
_gabor_ext_complex = gabor_feature_extractor.gabor_extractor_multi_scale(n_ori=n_ori, n_sf=n_sf)

screen_eccen_deg=8.4
sf_cyc_per_stim = _gabor_ext_complex.feature_table['SF: cycles per stim']
sf_cyc_per_deg = sf_cyc_per_stim/screen_eccen_deg
sf_unique, sf_inds = np.unique(sf_cyc_per_deg, return_inverse=True)

ori_deg = _gabor_ext_complex.feature_table['Orientation: degrees']
ori_unique, orient_inds = np.unique(ori_deg, return_inverse=True)

In [3]:
ori_unique

array([  0.,  45.,  90., 135.])

In [6]:
sf_unique.round(2)

array([0.36, 1.03, 2.97, 8.57])

In [15]:
import numpy as np

n_trn = 20

trninds = np.arange(n_trn)

n_iters = 10;
shuff_inds_trn = np.array([np.random.permutation(n_trn) for xx in range(n_iters)]).T

In [17]:
shuff_inds_trn.shape

(20, 10)

In [19]:
inds_use = np.array([2,10,12,13,14,15])
shuff_inds_trn_use = shuff_inds_trn[inds_use,:]
shuff_inds_trn_use

array([[14, 11,  1,  2, 12, 11,  3, 13, 13,  0],
       [15,  7, 14,  5,  7,  9, 10,  6,  8,  1],
       [17, 18,  3, 10, 15, 14, 16, 12,  4, 13],
       [16,  5,  6, 13, 19,  7,  4, 16,  3, 16],
       [ 0, 14,  8, 17, 18,  3,  7,  3, 11, 17],
       [19,  6, 18, 19, 17, 10, 18,  5,  5, 10]])

In [21]:
xx=5
un, inds = np.unique(shuff_inds_trn_use[:,xx], return_inverse=True)
inds

array([4, 2, 5, 1, 0, 3])

In [23]:
np.array([np.unique(shuff_inds_trn_use[:,xx], return_inverse=True)[1]\
         for xx in range(n_iters)]).T

array([[1, 3, 0, 0, 1, 4, 0, 4, 5, 0],
       [2, 2, 4, 1, 0, 2, 3, 2, 3, 1],
       [4, 5, 1, 2, 2, 5, 4, 3, 1, 3],
       [3, 0, 2, 3, 5, 1, 1, 5, 0, 4],
       [0, 4, 3, 4, 4, 0, 2, 0, 4, 5],
       [5, 1, 5, 5, 3, 3, 5, 1, 2, 2]])